function ERT_sim_report(cont_err,cont_err_amount,cont_true_err,cont_true_err_amount, ...
   sig_err,sig_win_rate,T3)

% Reports results of simulation for null/control (cont) and ERT/signal (sig))

fprintf(['Avg control error rate: ' num2str(mean(cont_err)) ' (' ...
   num2str(min(cont_err)) '-' num2str(max(cont_err)) ')\n']);
fprintf(['Control FWER: ' num2str(mean(cont_err > 0)*100) 'pc\n']);
fprintf(['Avg control error amount: ' num2str(mean(cont_err_amount,'omitnan')) ' (' ...
   num2str(min(cont_err_amount)) '-' num2str(max(cont_err_amount)) ')\n']);
fprintf(['Avg true error rate: ' num2str(mean(cont_true_err)) ' (' ...
   num2str(min(cont_true_err)) '-' num2str(max(cont_true_err)) ')\n']);
fprintf(['True control FWER: ' num2str(mean(cont_true_err > 0)*100) 'pc\n']);
fprintf(['Avg true error amount: ' num2str(mean(cont_true_err_amount,'omitnan')) ' (' ...
   num2str(min(cont_true_err_amount)) '-' num2str(max(cont_true_err_amount)) ')\n']);
fprintf(['Avg signal error rate: ' num2str(mean(sig_err)) ' (' ...
   num2str(min(sig_err)) '-' num2str(max(sig_err)) ')\n']);
fprintf(['Signal FWER: ' num2str(mean(sig_err > 0)*100) 'pc\n']);
fprintf(['Avg signal correct reject rate: ' num2str(mean(sig_win_rate)) ' (' ...
   num2str(min(sig_win_rate)) '-' num2str(max(sig_win_rate)) ')\n']);
fprintf(['FW correct reject rate: ' num2str(mean(sig_win_rate > 0)*100) 'pc\n']);
fprintf(['Avg signal T3 error rate: ' num2str(mean(T3)) ' (' ...
   num2str(min(T3)) '-' num2str(max(T3)) ')\n']);